# nixpacks.toml – instala Chromium completo + libs GTK/GLib
[phases.setup]
nixPkgs = [
  # Chromium com todas as dependências internas
  "chromium",

  # libs extras que o Puppeteer costuma exigir
  "nss_latest",
  "libxkbcommon",
  "gtk3",
  "alsa-lib"
]

# Diz explicitamente ao Nixpacks que queremos Node 18
[variables]
NODE_VERSION = "18"
